// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EstateAdministrationUI.IntegrationTests.Tests
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("MyEstate")]
    [NUnit.Framework.CategoryAttribute("base")]
    [NUnit.Framework.CategoryAttribute("shared")]
    public partial class MyEstateFeature
    {
        
        private Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "base",
                "shared"};
        
#line 1 "MyEstate.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, NUnit.Framework.TestContext.CurrentContext.WorkerId);
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Tests", "MyEstate", null, ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 4
#line hidden
            Reqnroll.Table table1 = new Reqnroll.Table(new string[] {
                        "Role Name"});
            table1.AddRow(new string[] {
                        "Estate"});
#line 6
 await testRunner.GivenAsync("I create the following roles", ((string)(null)), table1, "Given ");
#line hidden
            Reqnroll.Table table2 = new Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Description"});
            table2.AddRow(new string[] {
                        "estateManagement",
                        "Estate Managememt REST Scope",
                        "A scope for Estate Managememt REST"});
            table2.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST Scope",
                        "Scope for Transaction Processor REST"});
            table2.AddRow(new string[] {
                        "fileProcessor",
                        "File Processor REST Scope",
                        "Scope for File Processor REST"});
#line 10
 await testRunner.GivenAsync("I create the following api scopes", ((string)(null)), table2, "Given ");
#line hidden
            Reqnroll.Table table3 = new Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Secret",
                        "Scopes",
                        "UserClaims"});
            table3.AddRow(new string[] {
                        "estateManagement",
                        "Estate Managememt REST",
                        "Secret1",
                        "estateManagement",
                        "merchantId,estateId,role"});
            table3.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST",
                        "Secret1",
                        "transactionProcessor",
                        "merchantId,estateId,role"});
            table3.AddRow(new string[] {
                        "fileProcessor",
                        "File Processor REST",
                        "Secret1",
                        "fileProcessor",
                        "merchantId,estateId,role"});
#line 16
 await testRunner.GivenAsync("I create the following api resources", ((string)(null)), table3, "Given ");
#line hidden
            Reqnroll.Table table4 = new Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Description",
                        "UserClaims"});
            table4.AddRow(new string[] {
                        "openid",
                        "Your user identifier",
                        "",
                        "sub"});
            table4.AddRow(new string[] {
                        "profile",
                        "User profile",
                        "Your user profile information (first name, last name, etc.)",
                        "name,role,email,given_name,middle_name,family_name,estateId,merchantId"});
            table4.AddRow(new string[] {
                        "email",
                        "Email",
                        "Email and Email Verified Flags",
                        "email_verified,email"});
#line 22
 await testRunner.GivenAsync("I create the following identity resources", ((string)(null)), table4, "Given ");
#line hidden
            Reqnroll.Table table5 = new Reqnroll.Table(new string[] {
                        "ClientId",
                        "Name",
                        "Secret",
                        "Scopes",
                        "GrantTypes",
                        "RedirectUris",
                        "PostLogoutRedirectUris",
                        "RequireConsent",
                        "AllowOfflineAccess",
                        "ClientUri"});
            table5.AddRow(new string[] {
                        "serviceClient",
                        "Service Client",
                        "Secret1",
                        "estateManagement,transactionProcessor",
                        "client_credentials",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table5.AddRow(new string[] {
                        "estateUIClient",
                        "Merchant Client",
                        "Secret1",
                        "estateManagement,fileProcessor,transactionProcessor,openid,email,profile",
                        "hybrid",
                        "https://localhost:[port]/signin-oidc",
                        "https://localhost:[port]/signout-oidc",
                        "false",
                        "true",
                        "https://[url]:[port]"});
#line 28
 await testRunner.GivenAsync("I create the following clients", ((string)(null)), table5, "Given ");
#line hidden
            Reqnroll.Table table6 = new Reqnroll.Table(new string[] {
                        "ClientId"});
            table6.AddRow(new string[] {
                        "serviceClient"});
#line 33
 await testRunner.GivenAsync("I have a token to access the estate management resource", ((string)(null)), table6, "Given ");
#line hidden
            Reqnroll.Table table7 = new Reqnroll.Table(new string[] {
                        "EstateName"});
            table7.AddRow(new string[] {
                        "Test Estate"});
#line 37
 await testRunner.GivenAsync("I have created the following estates", ((string)(null)), table7, "Given ");
#line hidden
            Reqnroll.Table table8 = new Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "RequireCustomMerchantNumber",
                        "RequireCustomTerminalNumber"});
            table8.AddRow(new string[] {
                        "Test Estate",
                        "Test Operator",
                        "True",
                        "True"});
#line 41
 await testRunner.AndAsync("I have created the following operators", ((string)(null)), table8, "And ");
#line hidden
            Reqnroll.Table table9 = new Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName"});
            table9.AddRow(new string[] {
                        "Test Estate",
                        "Test Operator"});
#line 45
 await testRunner.AndAsync("I have assigned the following operators to the estates", ((string)(null)), table9, "And ");
#line hidden
            Reqnroll.Table table10 = new Reqnroll.Table(new string[] {
                        "EmailAddress",
                        "Password",
                        "GivenName",
                        "FamilyName",
                        "EstateName"});
            table10.AddRow(new string[] {
                        "estateuser@testestate1.co.uk",
                        "123456",
                        "TestEstate",
                        "User1",
                        "Test Estate"});
#line 49
 await testRunner.AndAsync("I have created the following security users", ((string)(null)), table10, "And ");
#line hidden
#line 53
 await testRunner.GivenAsync("I am on the application home page", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 55
 await testRunner.AndAsync("I click on the Sign In Button", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
 await testRunner.ThenAsync("I am presented with a login screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 59
 await testRunner.WhenAsync("I login with the username \'estateuser@testestate1.co.uk\' and password \'123456\'", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
 await testRunner.ThenAsync("I am presented with the Estate Administrator Dashboard", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create New Operator")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public async System.Threading.Tasks.Task CreateNewOperator()
        {
            string[] tagsOfScenario = new string[] {
                    "ignore"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Create New Operator", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 79
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
#line 80
 await testRunner.GivenAsync("I click on the My Estate sidebar option", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 81
 await testRunner.ThenAsync("I am presented with the Estate Details Screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
                Reqnroll.Table table11 = new Reqnroll.Table(new string[] {
                            "EstateName"});
                table11.AddRow(new string[] {
                            "Test Estate"});
#line 82
 await testRunner.AndAsync("My Estate Details will be shown", ((string)(null)), table11, "And ");
#line hidden
#line 85
 await testRunner.GivenAsync("I click on the My Operators sidebar option", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 86
 await testRunner.ThenAsync("I am presented with the Operators List Screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
                Reqnroll.Table table12 = new Reqnroll.Table(new string[] {
                            "OperatorName"});
                table12.AddRow(new string[] {
                            "Test Operator"});
#line 87
 await testRunner.AndAsync("the following operator details are in the list", ((string)(null)), table12, "And ");
#line hidden
#line 90
 await testRunner.WhenAsync("I click the Add New Operator button", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 91
 await testRunner.ThenAsync("I am presented the new operator screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
                Reqnroll.Table table13 = new Reqnroll.Table(new string[] {
                            "OperatorName"});
                table13.AddRow(new string[] {
                            "Test New Operator"});
#line 92
 await testRunner.WhenAsync("I enter the following new operator details", ((string)(null)), table13, "When ");
#line hidden
#line 95
 await testRunner.WhenAsync("I click the Create Operator button", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 96
 await testRunner.ThenAsync("I am presented with the Operators List Screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 97
 await testRunner.GivenAsync("I click on the My Operators sidebar option", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 98
 await testRunner.ThenAsync("I am presented with the Operators List Screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
                Reqnroll.Table table14 = new Reqnroll.Table(new string[] {
                            "OperatorName"});
                table14.AddRow(new string[] {
                            "Test Operator"});
                table14.AddRow(new string[] {
                            "Test New Operator"});
#line 99
 await testRunner.AndAsync("the following operator details are in the list", ((string)(null)), table14, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create New Contract")]
        [NUnit.Framework.CategoryAttribute("PRTest")]
        public async System.Threading.Tasks.Task CreateNewContract()
        {
            string[] tagsOfScenario = new string[] {
                    "PRTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Create New Contract", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 105
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
#line 106
 await testRunner.GivenAsync("I click on the My Contracts sidebar option", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 107
 await testRunner.ThenAsync("I am presented with the Contracts List Screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 109
 await testRunner.WhenAsync("I click the Add New Contract button", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 110
 await testRunner.ThenAsync("I am presented the new contract screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
                Reqnroll.Table table15 = new Reqnroll.Table(new string[] {
                            "OperatorName",
                            "ContractDescription"});
                table15.AddRow(new string[] {
                            "Test Operator",
                            "Test Contract"});
#line 111
 await testRunner.WhenAsync("I enter the following new contract details", ((string)(null)), table15, "When ");
#line hidden
#line 114
 await testRunner.WhenAsync("I click the Create Contract button", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 115
 await testRunner.ThenAsync("I am presented with the Contracts List Screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
                Reqnroll.Table table16 = new Reqnroll.Table(new string[] {
                            "ContractDescription"});
                table16.AddRow(new string[] {
                            "Test Contract"});
#line 116
 await testRunner.AndAsync("the following contract details are in the list", ((string)(null)), table16, "And ");
#line hidden
#line 120
 await testRunner.WhenAsync("I click the Products Link for \'Test Contract\'", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 121
 await testRunner.ThenAsync("I am presented with the Products List Screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 122
 await testRunner.WhenAsync("I click the Add New Product button", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 123
 await testRunner.ThenAsync("I am presented the new product screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
                Reqnroll.Table table17 = new Reqnroll.Table(new string[] {
                            "ProductName",
                            "DisplayText",
                            "Value",
                            "ProductType"});
                table17.AddRow(new string[] {
                            "100 KES Topup",
                            "100 KES",
                            "100.00",
                            "Mobile Topup"});
#line 124
 await testRunner.WhenAsync("I enter the following new product details", ((string)(null)), table17, "When ");
#line hidden
#line 127
 await testRunner.WhenAsync("I click the Create Product button", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 128
 await testRunner.ThenAsync("I am presented with the Products List Screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
                Reqnroll.Table table18 = new Reqnroll.Table(new string[] {
                            "ProductName"});
                table18.AddRow(new string[] {
                            "100 KES Topup"});
#line 129
 await testRunner.AndAsync("the following product details are in the list", ((string)(null)), table18, "And ");
#line hidden
#line 133
 await testRunner.WhenAsync("I click the Transaction Fees Link for \'100 KES Topup\'", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 134
 await testRunner.ThenAsync("I am presented with the Transaction Fee List Screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 135
 await testRunner.WhenAsync("I click the Add New Transaction Fee button", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 136
 await testRunner.ThenAsync("I am presented the new transaction fee screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
                Reqnroll.Table table19 = new Reqnroll.Table(new string[] {
                            "Description",
                            "CalculationType",
                            "FeeType",
                            "Value"});
                table19.AddRow(new string[] {
                            "Merchant Commission",
                            "Percentage",
                            "Merchant",
                            "0.05"});
#line 137
 await testRunner.WhenAsync("I enter the following new transaction fee details", ((string)(null)), table19, "When ");
#line hidden
#line 140
 await testRunner.WhenAsync("I click the Create Transaction Fee button", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 141
 await testRunner.ThenAsync("I am presented with the Transaction Fee List Screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
                Reqnroll.Table table20 = new Reqnroll.Table(new string[] {
                            "Description"});
                table20.AddRow(new string[] {
                            "Merchant Commission"});
#line 142
 await testRunner.AndAsync("the following fee details are in the list", ((string)(null)), table20, "And ");
#line hidden
#line 146
 await testRunner.GivenAsync("I click on the My Contracts sidebar option", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 147
 await testRunner.ThenAsync("I am presented with the Contracts List Screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
                Reqnroll.Table table21 = new Reqnroll.Table(new string[] {
                            "ContractDescription"});
                table21.AddRow(new string[] {
                            "Test Contract"});
#line 148
 await testRunner.AndAsync("the following contract details are in the list", ((string)(null)), table21, "And ");
#line hidden
#line 151
 await testRunner.WhenAsync("I click the Products Link for \'Test Contract\'", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 153
 await testRunner.ThenAsync("I am presented with the Products List Screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 154
 await testRunner.WhenAsync("I click the Add New Product button", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
                Reqnroll.Table table22 = new Reqnroll.Table(new string[] {
                            "ProductName",
                            "DisplayText",
                            "Value",
                            "ProductType"});
                table22.AddRow(new string[] {
                            "Custom Value Topup",
                            "Custom",
                            "",
                            "Mobile Topup"});
#line 155
 await testRunner.WhenAsync("I enter the following new product details", ((string)(null)), table22, "When ");
#line hidden
#line 158
 await testRunner.WhenAsync("I click the Create Product button", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 159
 await testRunner.ThenAsync("I am presented with the Products List Screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
                Reqnroll.Table table23 = new Reqnroll.Table(new string[] {
                            "ProductName"});
                table23.AddRow(new string[] {
                            "100 KES Topup"});
                table23.AddRow(new string[] {
                            "Custom Value Topup"});
#line 160
 await testRunner.AndAsync("the following product details are in the list", ((string)(null)), table23, "And ");
#line hidden
#line 165
 await testRunner.WhenAsync("I click the Transaction Fees Link for \'Custom Value Topup\'", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 166
 await testRunner.ThenAsync("I am presented with the Transaction Fee List Screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 167
 await testRunner.WhenAsync("I click the Add New Transaction Fee button", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 168
 await testRunner.ThenAsync("I am presented the new transaction fee screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
                Reqnroll.Table table24 = new Reqnroll.Table(new string[] {
                            "Description",
                            "CalculationType",
                            "FeeType",
                            "Value"});
                table24.AddRow(new string[] {
                            "Merchant Commission",
                            "Percentage",
                            "Merchant",
                            "0.05"});
#line 169
 await testRunner.WhenAsync("I enter the following new transaction fee details", ((string)(null)), table24, "When ");
#line hidden
#line 172
 await testRunner.WhenAsync("I click the Create Transaction Fee button", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 173
 await testRunner.ThenAsync("I am presented with the Transaction Fee List Screen", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
                Reqnroll.Table table25 = new Reqnroll.Table(new string[] {
                            "Description"});
                table25.AddRow(new string[] {
                            "Merchant Commission"});
#line 174
 await testRunner.AndAsync("the following fee details are in the list", ((string)(null)), table25, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
