name: Publish Pre-Release Nuget and Docker

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  build:
    name: "Publish Pre-Release Nugets and Docker"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2.3.4 
      with:
        fetch-depth: 0
        
    - name: Restore Nuget Packages
      run: dotnet restore EstateAdministrationUI.sln --source https://api.nuget.org/v3/index.json --source https://www.myget.org/F/transactionprocessing/api/v3/index.json

    - name: Build Code
      run: dotnet build EstateAdministrationUI.sln --configuration Release
         
    - name: Publish Images to Docker Hub
      run: |
        docker build . --file EstateAdministrationUI/Dockerfile --tag stuartferguson/estateadministrationui:master
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker push stuartferguson/estateadministrationui:master  
